local function configure_tex_buffer(bufnr)
	local map = function(lhs, rhs, desc)
		vim.keymap.set("n", lhs, rhs, {
			buffer = bufnr,
			silent = true,
			desc = desc,
		})
	end

	vim.opt_local.wrap = true
	vim.opt_local.linebreak = true
	vim.opt_local.breakindent = true
	vim.opt_local.spell = true
	vim.opt_local.spelllang = "en_us"
	vim.opt_local.conceallevel = 2

	-- Start or toggle VimTeX's continuous latexmk compiler.
	map("<leader>ll", "<cmd>VimtexCompile<cr>", "VimTeX compile")
	-- Open the PDF viewer or forward-search the current cursor position.
	map("<leader>lv", "<cmd>VimtexView<cr>", "VimTeX view PDF")
	-- Stop the currently running VimTeX compiler job.
	map("<leader>ls", "<cmd>VimtexStop<cr>", "VimTeX stop compiler")
	-- Remove LaTeX auxiliary files generated by compilation.
	map("<leader>lc", "<cmd>VimtexClean<cr>", "VimTeX clean auxiliaries")
	-- Show compiler and parser errors collected by VimTeX.
	map("<leader>le", "<cmd>VimtexErrors<cr>", "VimTeX errors")
end

return {
	{
		"lervag/vimtex",
		ft = { "tex", "latex" },
		init = function()
			vim.g.tex_flavor = "latex"

			vim.g.vimtex_compiler_method = "latexmk"
			vim.g.vimtex_compiler_latexmk = {
				continuous = 1,
				callback = 1,
				options = {
					"-pdf",
					"-synctex=1",
					"-interaction=nonstopmode",
					"-file-line-error",
				},
			}

			if vim.fn.executable("zathura") == 1 then
				vim.g.vimtex_view_method = "zathura"
			elseif vim.fn.executable("okular") == 1 then
				vim.g.vimtex_view_method = "okular"
			end

			vim.g.vimtex_syntax_conceal = {
				accents = 1,
				cites = 1,
				fancy = 1,
				greek = 1,
				math_bounds = 1,
				math_delimiters = 1,
				math_fracs = 1,
				math_symbols = 1,
				sections = 0,
				styles = 1,
			}
		end,
		config = function()
			local group = vim.api.nvim_create_augroup("vimtex_buffer_config", { clear = true })

			vim.api.nvim_create_autocmd("FileType", {
				group = group,
				pattern = { "tex", "latex" },
				callback = function(args)
					configure_tex_buffer(args.buf)
				end,
			})

			local current_ft = vim.bo.filetype
			if current_ft == "tex" or current_ft == "latex" then
				configure_tex_buffer(vim.api.nvim_get_current_buf())
			end
		end,
	},
}
